=== PitStop13/TPSI-Esercizi/2025-26/Ottobre/DTD/Address List/address.dtd
<!ELEMENT AddressContenitore (Informazione+)>  

<!-- + indica che devo avere ALMENO 1 elemento-->
<!-- ? indica che puoi averne o 1 o nessuna -->
<!-- * indica che puoi sia averne che non (0,1,2,3...) -->

<!ELEMENT Informazione (nome,indirizzo*,numTelefono*,mail*,nazionalità?,note*)>

<!ELEMENT nome (nomeProprio,secondoNome*,cognome)>
<!ELEMENT nomeProprio (#PCDATA)>
<!ELEMENT secondoNome (#PCDATA)>
<!ELEMENT cognome (#PCDATA)>

<!ELEMENT indirizzo (via+,indirizzoPostale,provincia?,paese+)>
<!ELEMENT via (#PCDATA)>
<!ELEMENT indirizzoPostale (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT paese (#PCDATA)>

<!ELEMENT numTelefono (#PCDATA)>
<!ELEMENT mail (#PCDATA)>
<!ELEMENT nazionalità (#PCDATA)> 
<!ELEMENT note (#PCDATA)>

=== PitStop13/TPSI-Esercizi/2025-26/Ottobre/DTD/Address List/address.xml
<!DOCTYPE AddressContenitore SYSTEM "address.dtd">

<AddressContenitore>
    <Informazione>
        <nome>
            <nomeProprio></nomeProprio>
            <secondoNome></secondoNome>
            <cognome></cognome>
        </nome>
    
        <indirizzo>
            <via></via>
            <indirizzoPostale></indirizzoPostale>
            <provincia></provincia>
            <paese></paese>
        </indirizzo>
    
        <numTelefono></numTelefono>
        <mail></mail>
        <nazionalità></nazionalità>
        <note></note>
    </Informazione>
</AddressContenitore>
