=== PitStop13/TPSI-Esercizi/2025-26/Ottobre/DTD/Lettera/lettera.dtd
<!ELEMENT letteraContenitore (lettera+)>  

<!-- + indica che devo avere ALMENO 1 elemento-->
<!-- ? indica che puoi averne o 1 o nessuna -->
<!-- * indica che puoi sia averne che non (0,1,2,3...) -->

<!ELEMENT lettera (mittente,data,dest,oggetto,saluto,corpo,chiusura,firma)>

<!ELEMENT mittente (#PCDATA)> 
<!ELEMENT data (#PCDATA)>
<!ELEMENT dest (#PCDATA)>
<!ELEMENT oggetto (#PCDATA)>
<!ELEMENT saluto (#PCDATA)> 
<!ELEMENT corpo (paragrafo+)>
<!ELEMENT paragrafo (#PCDATA)>
<!ELEMENT chiusura (#PCDATA)>
<!ELEMENT firma (#PCDATA)>

=== PitStop13/TPSI-Esercizi/2025-26/Ottobre/DTD/Lettera/lettera.xml
<!DOCTYPE letteraContenitore SYSTEM "lettera.dtd">

<letteraContenitore>
    <lettera>
        <mittente></mittente>
        <data></data>
        <dest></dest>
        <oggetto></oggetto>
        <saluto></saluto>
        <corpo>
            <paragrafo></paragrafo>
        </corpo>
        <chiusura></chiusura>
        <firma></firma>
    </lettera>
</letteraContenitore>
